### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by osbm** [giswqs/streamlit-geospatial#58]
The streamlit app doesn't load

**Comment by giswqs** [comment]
App rebooted. Should be working now.

**Comment by osbm** [comment]
This link is still broken
https://geospatial.streamlitapp.com/
